require:
  - rubocop-rake
#  - rubocop-rspec # TODO: Disabling for now. Too many offences to be dealt with and are not part of gem's shipped code.

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - features/**/*
    - .bundle/**/*
    - bundle_bin/**/*
    - vendor/bundle/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '*.gemspec'
    - '**/*.rake'
    - 'spec/**/*spec.rb'

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Max: 20
